site_name: 开水的小壶
site_description: 随缘记录
site_url: https://Altokra.github.io/

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.follow

plugins:
  - search
  - callouts

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - 首页: index.md
  - 关于我: about.md
  - 项目: projects.md
  - 杂项:
      - 网站搭建记录: others/website.md

